### ISSUE TITLE
[Feature request] Add sqlite

### ISSUE THREAD

**Issue by michaelpetri** [geertw/docker-php-ci#5]
Hi,

first of all, thanks for this nice image, it fits 99% of my requirements.
For the last 1% it would be great if you would add sqlite to your Dockerfile, your image should stay slim as it already is.

Best regards
Michael

**Comment by geertw** [comment]
Hi, isn't sqlite already included in all PHP images by default?

```
geert@luna ~ $ docker run geertw/docker-php-ci:5.6 -it | grep SQLite
PDO Driver for SQLite 3.x => enabled
SQLite Library => 3.8.10.2
SQLite3 support => enabled
SQLite3 module version => 0.7-dev
SQLite Library => 3.8.10.2
```

**Comment by michaelpetri** [comment]
Hi, 

i received an error in my pipeline when i switched over to your image so i installed sqlite3 libsqlite3-dev and everything worked for me. 

I'll check this again and let you know, thanks for your feedback.

**Comment by geertw** [comment]
Do you mean the `sqlite` command or sqlite support in PHP? I was referring to the latter, but the sqlite command is not build in, so when you need that, let me know.

**Comment by michaelpetri** [comment]
Hi, 

i tested it again and i don't understand what i've done before and why i received a sqlite error but now everything works fine out of the box :) Sorry for bothering you and again thanks for this image and for keeping it up2date!

**Comment by geertw** [comment]
No problem, glad you enjoy it!

**Comment by michaelpetri** [comment]
Me again, 

found the problem. The cli tool i use requires the sqlite command(!). So if possible it would be great if you could add it to your image. This would speed up my build job :D 

Best regards
Michael

**Comment by geertw** [comment]
I see :-) It's included now!
