### ISSUE TITLE
fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by Sarke** [geertw/docker-php-ci#6]
Thanks for the nice docker image!

Can I suggest you add the following?

    composer global require "fxp/composer-asset-plugin:^1.4"

It is used by Yii2 (amongst other projects) to allow NPM and Bower assets to be used by composer.  It also can't be installed in the project scope (needs to be global).

**Comment by geertw** [comment]
It is now added! Normally I would be a bit reluctant to adding these type of dependencies (I'm aiming to keep the images small), but as I'm an avid Yii2 user myself, I can see it's useful.
